version: '3.8'

services:

  server:
    image: "go_goss/server"
    container_name: "go_gossgo run cmd/migrate/main.go_container"
    env_file:
      - .env
    environment:
      - API_HOST=0.0.0.0
      - DB_HOST=postgres
      - DB_PORT=5432
      - OTEL_OTLP_ENDPOINT=otel-collector:4317
      - REDIS_HOST=valkey
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${API_PORT}:${API_PORT}
